### ISSUE TITLE
Accessibility: Bootstrap alert alert-warning contrast ratio

### ISSUE THREAD

**Issue by r1teshkumar** [US-CBP/cbp-theme#102]
CBP Theme

![image](https://user-images.githubusercontent.com/22313231/28435949-278421e2-6d63-11e7-95f9-10bb74a1dbec.png)

Previous Generation Theme
![image](https://user-images.githubusercontent.com/22313231/28435960-36ab341c-6d63-11e7-848e-9e050aafa867.png)

**Comment by davezen1** [comment]
@r1teshkumar what version are you using?  See the latest contrast ratio in the Kitchen Sink:

<img width="1554" alt="screen shot 2017-07-21 at 7 45 22 am" src="https://user-images.githubusercontent.com/1034574/28462407-1fd301a8-6de9-11e7-8c6a-2c62e4e4ccac.png">

**Comment by r1teshkumar** [comment]
@davezen1 , you are right, while this looks very similar to base bootstrap, looks like it is just different enough to pass contrast ratio test.
