### ISSUE TITLE
Modularize Distributed SASS Files

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#103]
As a developer, I would like the distributed SASS files to be separated into modules that are distinct such as core, variables, bootstrap, mdl, so that I can use only the files I need.

- Request for a main or core.scss that serves as the base for all projects and starters
- Request to create separate bootstrap related sass files
- Request to create separate material design lite sass files

cc @djKianoosh @martin-the-geek @yogeshgadge

**Comment by yogeshgadge** [comment]
Copying @dave-r

**Comment by LaurenFormichella** [comment]
Just creeping through - keep up the great work!

**Comment by yogeshgadge** [comment]
My thoughts:-

If I remember I believe the intention and ultimate end goal is the following:-

- Changes to `cbp-theme` can be delivered to consumer applications via SCSS without forcing the them to write their applications mixing `mdl-` or `bootstrap` namespace and other libraries that `cbp-theme` may use.

I believe this is only possible in 2 ways;-

1) That `cbp-theme` exposes every component in a consistent namespace somethings like `cbp-`. This I believe may not be realistic and essentially requires `cbp-theme` to re-implement the `kitchensink` and `cbp-style-guide` without `mdl-` and without `bootstrap`. This requires lot of work for `cbp-theme`.

2) That the consumer applications must only use `variables` and compose their css using these variables. This limits the namespace only to the variable names which much of the markup is is clean. This requires all the variables to be explicitly defined inside `cbp-theme`.  Also every css must be defined with values from variables.
