### ISSUE TITLE
cards broken on style guide

### ISSUE THREAD

**Issue by yellowzapp** [US-CBP/cbp-theme#106]
https://us-cbp.github.io/cbp-style-guide/docs/components/cards.html

the module here is broken in IE

**Comment by r1teshkumar** [comment]
Doesn't render properly in IE and this may be an underlying issue with the Card CSS itself. See use of flexbox.

**IE - Stretched and not rendering correctly **
![cards-ie](https://user-images.githubusercontent.com/22313231/29092373-1fd59624-7c54-11e7-825f-2a3adc4369c7.png)

**Chrome - more proportionate**
![cards-chrome](https://user-images.githubusercontent.com/22313231/29092382-220561e0-7c54-11e7-8588-f367e8dc80bb.png)

**Comment by mkayan** [comment]
This issue is fixed in style guide.
