### ISSUE TITLE
Module not found: `/node_modules/jQuery/dist/jquery.js` does not match the corresponding path on disk `jquery`.

### ISSUE THREAD

**Issue by d-amit** [US-CBP/cbp-theme#107]
When using facebooks app starter (create-react-app) which also abstracts the webpack config from the standard implementation (w/o ejecting), cbp-theme.js external dependency mapping is looking for jQuery instead of jquery. I wanted to get cbp-theme working without ejecting since once app implementation is ejected its can't be reverted and it cant take advantage of updates in the future to the react-scripts.

**Expected Behavior**
It would have pulled the jquery dependency and run the application.

**Actual Behavior**
`./node_modules/cbp-theme/dist/cbp-theme.js
Module not found: `/node_modules/jQuery/dist/jquery.js` does not match the corresponding path on disk `jquery`.`

<img width="1437" alt="screen shot 2017-08-10 at 2 30 53 pm" src="https://user-images.githubusercontent.com/14062379/29186026-352296ea-7dd9-11e7-9162-d4f0add9e99d.png">

**Steps to replicate**
- Run ```yarn global add create-react-app```
- ```create-react-app my-app```
- ```cd my-app/```
- ```yarn add jquery cbp-theme```
- in the index.js (entry), add your cbp-theme dependencies like (css and js)
- Run ```yarn start```

Here's what my index.js looks like...
<img width="710" alt="screen shot 2017-08-10 at 2 24 34 pm" src="https://user-images.githubusercontent.com/14062379/29185597-b6a0a06a-7dd7-11e7-968f-935bf6aefcc0.png">

**Comment by davezen1** [comment]
@d-amit can you confirm the latest release 1.3.2 fixes the problem?

**Comment by davezen1** [comment]
@d-amit  confirmed fix.
