### ISSUE TITLE
Buttons instead of links in navbar

### ISSUE THREAD

**Issue by jscharett** [US-CBP/cbp-theme#109]
It would be nice to be able to use buttons in place of links for some instances inside a nav bar.  In working with the cbp banner, there are a couple of drop downs that use a link to open them up.  It would be preferable to use a button rather than a link with role button as its more semantic and you don't need to worry about the accessibility differences between links/buttons.

**Comment by jscharett** [comment]
This is further complicated in Angular as the `#` used by the links causes the Angular routing to change.  Would be nice to be able to use standard buttons vs dummy links.

**Comment by djKianoosh** [comment]
Another option is to just use the javascript:void style of href links. Won't affect hash routes that way.

**Comment by djKianoosh** [comment]
But yeah, buttons with roles more correct semantically.
