### ISSUE TITLE
Convert cbp-theme custom JS from IIFE to modules

### ISSUE THREAD

**Issue by d-amit** [US-CBP/cbp-theme#110]
The current implementation of the cbp-theme custom JS should be updated to be modules that can be imported and called when needed.  The current implementation only works if the DOM is ready when the IIFEs are called.  When using React, NG, or Vue, there will be times the functions need to called on render of the components.

**Comment by davezen1** [comment]
@yogeshgadge are you having issues with the JS in ngx?

**Comment by yogeshgadge** [comment]
We don't have any problem because we don't/can't use any DOM manipulating
JS from cbp-theme.

**Comment by yogeshgadge** [comment]
We should have explicit render/apply function rather than execute on load. I will add this to rollupification work.

**Comment by yogeshgadge** [comment]
Rullupification #206 fixes this
