### ISSUE TITLE
j508 Accessibility Helper for Development

### ISSUE THREAD

**Issue by NoodleOfDeath** [US-CBP/cbp-theme#113]
Just a little script that attempts to clean up a webpage for development post-facto:

https://github.com/NoodleOfDeath/j508

**Comment by cmterrylynn** [comment]
Um, with a name like that, no way I'm opening this.

________________________________
From: Thom Morgan
Sent: Wednesday, August 16, 2017 5:50:01 PM
To: US-CBP/cbp-theme
Cc: Subscribed
Subject: [US-CBP/cbp-theme] j508 Hacky Script (#113)


Just a little script that attempts to clean up a webpage for development post-facto:

https://github.com/NoodleOfDeath/j508

**Comment by NoodleOfDeath** [comment]
NoodleOfDeath is my StackOverflow name... just read the GitHub source code!

**Comment by NoodleOfDeath** [comment]
This is Thom Morgan btw...

**Comment by djKianoosh** [comment]
An example or two might help... Also something in the readme to show general usage and what you get out of it... I was thinking it might nice to use during development to spit out where in the codebase the developer missed some accessibility markup. There are other tools out there for this though for sure...

**Comment by davezen1** [comment]
...and maybe we talk IRL.
