### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by HMcFabulous** [US-CBP/cbp-theme#133]
Change the timeline node icons to grey background. Current colorization of each node is distracting and interferes with comprehension. (Yes, it was prettier, but to its own detriment.). Grey will make it easier to scan information and still hold linear structure.

Revision example:
![timeline_hm](https://user-images.githubusercontent.com/11233429/30342879-6baa8268-97c9-11e7-8507-51a95e112c4c.jpg)

**Comment by d-amit** [comment]
Related to #40

**Comment by djKianoosh** [comment]
the gray makes me sad
