### ISSUE TITLE
Adjust grid breakpoint of page on scale

### ISSUE THREAD

**Issue by HMcFabulous** [US-CBP/cbp-theme#150]
The medium breakpoint of the page should not go to 100%. 
Additionally I would suggest when using a sidebar that has a fixed width - that we have a "slimmer" fixed width for the medium scale. I am not suggesting that we eliminate fixed width in the sidebar and have it be fluid - just that we have a medium and large fixed width calculation.

![grid-breakpoint](https://user-images.githubusercontent.com/11233429/30926932-c352b17c-a384-11e7-916c-78a6626ef852.png)

**Comment by mkayan** [comment]
This issue is fixed with theme version 1.7
