### ISSUE TITLE
App Header Wrapping

### ISSUE THREAD

**Issue by HMcFabulous** [US-CBP/cbp-theme#165]
The grey Application header does not scale appropriately when the browser window is reduced in size. The Application level header is not intended to be more than one line/ row in height at any given time. 
![app_header_wrap](https://user-images.githubusercontent.com/11233429/31451938-81730d0e-ae7b-11e7-94d2-930e887778c6.jpg)

**Comment by r1teshkumar** [comment]
Example layout has been fixed and published on CBP theme kitchen sink, same has to be done separately in the style guide layouts.
