### ISSUE TITLE
default background color

### ISSUE THREAD

**Issue by yellowzapp** [US-CBP/cbp-theme#169]
Can we add the default gray (f6f6f6) to the style guide? We already use it as the background color for the sidebar and other areas. It's just not listed currently. 

thanks,

Jeremy Caldwell

**Comment by yellowzapp** [comment]
@r1teshkumar  @jfinest 
yeah i think it needs to be added to the style guide too. needs to be added to theme as gray-lightest. that would follow the existing color naming convention. This is related to a few other issues with background colors in popovers having seemingly random colors assigned. (#f7f7f7 for example)

**Comment by yellowzapp** [comment]
escalating into a ticket

**Comment by davezen1** [comment]
fixed
