### ISSUE TITLE
Inconsistent $brand-warning: label-warning, badge-warning, text-warning

### ISSUE THREAD

**Issue by r1teshkumar** [US-CBP/cbp-theme#171]
Current *Theme* and *Style Guide*: text-warning has lost the color
![image](https://user-images.githubusercontent.com/22313231/31826713-ccf05066-b583-11e7-9166-7b7f594f7068.png)

*Prior Version of Theme*: Some random brown color

![image](https://user-images.githubusercontent.com/22313231/31826747-e1630da4-b583-11e7-9fd3-3ebfe792c178.png)

*Fix*
![image](https://user-images.githubusercontent.com/22313231/31826755-e94ee1f0-b583-11e7-8d17-04253c2a300e.png)

**Comment by r1teshkumar** [comment]
I meant *Badge Warning* for the second example =)

**Comment by r1teshkumar** [comment]
Fix actually seems to have contrast issues on default text size and font weights

![contrastratio](https://user-images.githubusercontent.com/22313231/31829718-1fd0ad14-b58c-11e7-82ca-d81ad788f1c1.png)

text-warning works with one of the font-awesome icons

![image](https://user-images.githubusercontent.com/22313231/31827303-56d940f2-b585-11e7-8fe4-5e23ae09e1b1.png)

**Comment by mkayan** [comment]
This issue is fixed with release 1.7.1
