### ISSUE TITLE
JQuery Syntax Error in Nav Bar

### ISSUE THREAD

**Issue by jshankman** [US-CBP/cbp-theme#18]
After playing around in the Kitchen Sink, it has come to my attention that the links inside the navbar buttons (in the app-header class) result in an unrecognized expression syntax error when calling the JQuery. I've attached a screenshot example of the issue. 

With this in mind, it is not possible to create links in the app-header navbar.

![image](https://cloud.githubusercontent.com/assets/5479666/16852577/a8d7306a-49d6-11e6-9c4e-7f565e51b173.png)

**Comment by d-amit** [comment]
Hi Jake can you use the un-minified jquery js file and document the full stack trace.  That will help us identify the root cause of the error.

**Comment by jshankman** [comment]
Below is the full stack trace, using all un-minified javascript files.
![image](https://cloud.githubusercontent.com/assets/5479666/16916030/c667aa70-4cc8-11e6-9596-d352edaf8444.png)

**Comment by d-amit** [comment]
@jshankman - Please pull the latest and confirm that the fix has resolved the issue.

**Comment by jshankman** [comment]
Completely removing the role="tab" (and tab data toggles) inside the <a>...</a> combined with adding the role="presentation" to the parent did the trick!
