### ISSUE TITLE
Checkbox/Radio replacement

### ISSUE THREAD

**Issue by jscharett** [US-CBP/cbp-theme#190]
It would be nice if the theme provided a simple checkbox/radio replacement to beautify and normalize those controls.  I know Material is the current standard, but for those not using Material, it would be nice to have something else.  A simple CSS replacement like what was done for the toggle switch.

**Comment by yellowzapp** [comment]
merging with related ticket 
https://github.com/US-CBP/cbp-theme/issues/217
