### ISSUE TITLE
Update to use Bootstrap 4

### ISSUE THREAD

**Issue by d-amit** [US-CBP/cbp-theme#2]
Update the CBP-theme bootstrap aspect from 3 to 4. If there are any gotchas or changes in the use of current bootstrap classes, please document in this issue or the wiki.

**Comment by jscharett** [comment]
Would be nice to see this re-opened.  Bootstrap 4 has a lot of nice features and would be nice to start working on migrating towards; assuming bootstrap is still the future of cbp-theme.  Maybe start an alpha release for bootstrap 4?

**Comment by davezen1** [comment]
@jscharett checkout https://github.com/US-CBP/cbp-theme/wiki/CBP-Theme-Roadmap
We will collect feedback for the next major version of the CBP Theme.

**Comment by jscharett** [comment]
Ok. Thanks. Is the best way to provide the feedback by submitting issues?

**Comment by davezen1** [comment]
@jscharett See #172
