### ISSUE TITLE
Update custom MDL select (select2 and selectize) so getDirty like method is part of the select2/selectize singleton.

### ISSUE THREAD

**Issue by d-amit** [US-CBP/cbp-theme#20]
Currently the custom JS in cbp-theme looks for all selectize or select2 components and adds on a change listener to the components to add or remove 'is-dirty' class to apply MDL label animations.

**Issue**: 
If application renders dom on the fly  or is using React, the components are not present when the cbp-theme custom js is ran so those components dont have the getDirty method applied to them.  

**Proposed solution**: 
If we add logic to the singletons of select2 and selectize ( if they are present), that adds the logic to remove/add 'is-dirty' class on change of value.  If anyone has an alternative solutions, please elaborate on this issue.  Maybe override onChange to include this logic and extend previous onChange logic.

**Current Workaround**:
For my case, on the React event componentDidUpdate I run getDirty logic.

[Current Implementation ](https://github.com/US-CBP/cbp-theme/blob/master/app/js/app_thirdparty_select.js)

**Comment by d-amit** [comment]
I suspect alot of our custom JS may run into this issue so we may can just open new issues as we run into them.

**Comment by d-amit** [comment]
Resolved by #23.

**Comment by davezen1** [comment]
It looks like there is no cbp-theme.min.css when running npm run build. Also, in package.json: 
  "main": "./dist/js/npm" is no longer needed.
