### ISSUE TITLE
Remove default navbar margin

### ISSUE THREAD

**Issue by jscharett** [US-CBP/cbp-theme#200]
I think base navbar class should not get the same 18px margin as the other 3 here.  It too generic.  Should be removed or scoped under a different selector.

```
.app-header, .app-header-bottom, .cbp-header, .navbar {
    position: relative;
    min-height: 50px;
    margin-bottom: 18px;
    border: 1px solid transparent;
}
```

**Comment by yellowzapp** [comment]
merging to a related ticket https://github.com/US-CBP/cbp-theme/issues/238
