### ISSUE TITLE
Fixing Security Vulnerability Reported 

### ISSUE THREAD

**Issue by r1teshkumar** [US-CBP/cbp-theme#222]
![image](https://user-images.githubusercontent.com/22313231/39327604-7e9c1c02-4966-11e8-8cf8-c844db6aea94.png)

**Comment by r1teshkumar** [comment]
Noticed this on the first page, probably should address it for the next patch version.

**Comment by djKianoosh** [comment]
Please see audit report from `npm audit`

[cbp-theme.audit.log](https://github.com/US-CBP/cbp-theme/files/2000951/cbp-theme.audit.log)

**Comment by djKianoosh** [comment]
Recommendations from `npm audit`:

```
Run  npm install --dev babel-preset-env@1.7.0  to resolve 123 vulnerabilities
Run  npm install --dev browser-sync@2.24.4  to resolve 21 vulnerabilities
Run  npm install --dev babel-core@6.26.3  to resolve 14 vulnerabilities
Run  npm install --dev node-sass@4.9.0  to resolve 2 vulnerabilities
Run  npm install --dev rollup-plugin-sass@0.6.1  to resolve 2 vulnerabilities
Run  npm update fsevents --depth 6  to resolve 72 vulnerabilities
Run  npm update fill-range --depth 12  to resolve 69 vulnerabilities
Run  npm update lodash --depth 10  to resolve 64 vulnerabilities
Run  npm update babel-core --depth 4  to resolve 30 vulnerabilities
Run  npm update babel-generator --depth 7  to resolve 11 vulnerabilities
Run  npm update istanbul-api --depth 2  to resolve 10 vulnerabilities
```

**Comment by djKianoosh** [comment]
I've created a branch to make these updates. Need a few of you to grab it, run the build and make sure things are ok:

https://github.com/US-CBP/cbp-theme/tree/npm-audit-vulnerabilities

**Comment by djKianoosh** [comment]
Some deps could stand to be updated:
![image](https://user-images.githubusercontent.com/222783/40002841-d858e4a8-575f-11e8-80b7-3b77e4b99d8b.png)

**Comment by yogeshgadge** [comment]
Will take a look tomorrow. I don't see we will have any issues.
