### ISSUE TITLE
Limit Roboto font types included

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#229]
As a developer, I would like to limit the fonts that are distributed with the CBP Theme to only woff and woff2 and if possible make it easy to include the Roboto fonts myself.

cc @djKianoosh @arakelian @HMcFabulous @yogeshgadge

**Comment by yellowzapp** [comment]
I agree. 

internet explorer will pull in the .woff file, all other browsers will pull in the .woff2 file. Eliminate the bloat of .ttf, .svg, etc. in roboto fonts.

**Comment by djKianoosh** [comment]
Please eliminate the bloat.

**Comment by yogeshgadge** [comment]
FYI - To those who might create a PR

Checkout `node_modules/roboto-fontface/css/mixins.scss` or how it is used and provide equivalent - basically user only the font files from roboto-fontface and reconstruct SCSS using a similar mixin as shown below.

Also FYI IE 11 does not pull '.woff' file - it is pulling only '.eot' files in my app even though I have everything included. Another interesting thing is I see is Chrome pulls fewer woff2 files compared to number of .eot files pulled by IE 11. Not sure why.

```
//node_modules/roboto-fontface/css/mixins.scss
@mixin roboto-font($folder, $variant, $type, $weight, $style) {

    $font-full-path: '#{$roboto-font-path}/#{$folder}/#{$variant}';

    @font-face {
        font-family: '#{$variant}';
        src: url('#{$font-full-path}-#{$type}.eot');
        src: local('#{$variant} #{$type}'),
             local('#{$variant}-#{$type}'),
             url('#{$font-full-path}-#{$type}.eot?#iefix') format('embedded-opentype'),
             url('#{$font-full-path}-#{$type}.woff2') format('woff2'),
             url('#{$font-full-path}-#{$type}.woff') format('woff'),
             url('#{$font-full-path}-#{$type}.ttf') format('truetype'),
             url('#{$font-full-path}-#{$type}.svg##{$variant}') format('svg');
        font-weight: $weight;
        font-style: $style;
    }

    @font-face {
        font-family: '#{$variant}-#{$type}';
        src: url('#{$font-full-path}-#{$type}.eot');
        src: local('#{$variant} #{$type}'),
             local('#{$variant}-#{$type}'),
             url('#{$font-full-path}-#{$type}.eot?#iefix') format('embedded-opentype'),
             url('#{$font-full-path}-#{$type}.woff2') format('woff2'),
             url('#{$font-full-path}-#{$type}.woff') format('woff'),
             url('#{$font-full-path}-#{$type}.ttf') format('truetype'),
             url('#{$font-full-path}-#{$type}.svg##{$variant}') format('svg');
    }
}
```

**Comment by yellowzapp** [comment]
there is one last existing issue with this relating to the path but should be fixed soon. 

please be sure to check the releases tab for more information.
