### ISSUE TITLE
Use Webpack as the bundler

### ISSUE THREAD

**Issue by apobbati** [US-CBP/cbp-theme#23]
Can we investigate the use of Webpack to bundle the final distribution?

Gulp can get quite convoluted.

**Comment by walhow** [comment]
Are we at the point where we could have an internal npm repo, that all teams could use to build from?

**Comment by djKianoosh** [comment]
It's still a little ways off. in the meantime we've been using the internal bitbucket server. not ideal but it's definitely on the radar

**Comment by millerbennett** [comment]
Is anyone already working on this? I'd be happy to pitch in on moving to webpack.

**Comment by djKianoosh** [comment]
by all means, please do

**Comment by walhow** [comment]
Could you keep me in the loop on this, such as which tool combinations work
(and we have access to) in our environment, I'd like to move our project to
webpack or other module loader over the next iteration. Thanks!

**Comment by d-amit** [comment]
IF no one has taken on this task, I have some bandwidth so I can get started on it.

**Comment by apobbati** [comment]
Go for it. If you need some help on it, i'll stop by later.

**Comment by davezen1** [comment]
The generated files should be plain js not in the webpack bundle format. 
 @martin-the-geek @XavierM what are your suggestions for the distribution?

**Comment by djKianoosh** [comment]
shouldn't they just be in a universally accepted module format though? that way anybody can consume it? this is the price you pay for being a library author.

**Comment by davezen1** [comment]
@tma001 
Let's test this out with multiple projects now that we have the 1.0.0 release
