### ISSUE TITLE
Labels that are also links need to preserve the original colors

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#231]
When labels are anchor tags in list groups, list group items their color is not preserved.  Suggested fix:

.list-group .list-group-item a:not(.label-info):not(.label-success) {
  color: #00416a !important;
}

.list-group .list-group-item a.label-info {
  color: #fff !important;
}

**Comment by phirephox** [comment]
Issue Addressed in pull request #247

**Comment by r1teshkumar** [comment]
@davezen1 , issue has been fixed and merged in master.
