### ISSUE TITLE
Suggestion for page header and hr style for accessibility

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#233]
For accessibility, suggesting updating page-header and hr styles to use @gray-light #808080 

/* CBP Theme Suggestion */
.page-header {
  border-bottom: 1px solid #808080;/* @gray-light */
  margin-bottom: 10px !important;
}
hr {
  border: none;
  height: 1px;
  color: #808080;
  background-color: #808080;/* @gray-light */
}

**Comment by yellowzapp** [comment]
@davezen1 are we talking just the horizontal rule that would effectively underline the page's title in the content area ? or all horizontal rules?

**Comment by yellowzapp** [comment]
ticket seems to be related to https://github.com/US-CBP/cbp-theme/issues/213
