### ISSUE TITLE
Lessen space between vertical checkboxes

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#235]
Suggestion: There is too much spacing between vertical checkboxes.

/** CBP Theme Suggested Fix */
.checkbox {
  margin-bottom: 3px !important;
}

@djKianoosh @HMcFabulous

**Comment by yellowzapp** [comment]
default spacing in style guide seems fine to me. Can we close this ticket? @djKianoosh 

https://us-cbp.github.io/cbp-style-guide/docs/components/formControls.html

<img width="703" alt="screen shot 2018-06-27 at 10 54 25 am" src="https://user-images.githubusercontent.com/30844514/41982091-881b2e68-79f8-11e8-8fe0-c00c0a7f4a81.png">
