### ISSUE TITLE
Proper word wrap for tooltip

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#236]
Suggestion tooltip should have word-wrap for .tooltip-inner class

To recreate use a long string in a tooltip.

<img width="398" alt="screen shot 2018-07-10 at 12 53 41 pm" src="https://user-images.githubusercontent.com/1034574/42525115-58773f92-8440-11e8-989b-1b78e748fc2e.png">

/** CBP Theme Fix */
.tooltip-inner {
  word-wrap: break-word !important;
}

@djKianoosh @HMcFabulous

**Comment by phirephox** [comment]
Please See Pull Request #246
