### ISSUE TITLE
Adjust CBP Header so that menus appear on top when scrolling

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#237]
The menus in the universal header float underneath the app header when scrolling
![image](https://user-images.githubusercontent.com/1034574/41381053-73c56286-6f34-11e8-8f1e-ccfbad1506c4.png)

@djKianoosh @HMcFabulous

**Comment by yellowzapp** [comment]
merging all header issues into one ticket 

https://github.com/US-CBP/cbp-theme/issues/238
