### ISSUE TITLE
Wrong background for nav bar links

### ISSUE THREAD

**Issue by jscharett** [US-CBP/cbp-theme#239]
The links in the CBP main nav bar at top of page, used to show application menu and whatnot, have a variant of blue background when active.  Its slightly different then the color used for the navbar itself

**Comment by jscharett** [comment]
```
.cbp-header: {background-color: #003e65;}
.cbp-header .navbar-nav>.open>a: {background-color: #00416a;}
```

**Comment by yellowzapp** [comment]
we are currently evaluating some pallete issues. please check back on our releases page to see changes made to the theme.
