### ISSUE TITLE
Allow for CBP Header and App Header to be fixed

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#240]
As a developer, I would like the option to make the cbp header (Universal Header) and app header fixed so that the users can always get to the universal header info/links if needed.

Right now we need to override the theme to make it fixed:

/* CBP Theme Override for Fixed Header and Navbar scroll */
.app-header.top {
  top: 50px !important;
  z-index: 1000 !important;
} 

In the html for cbp-header, add navbar-fixed-top

<div role="navigation" class="cbp-header navbar-fixed-top">

@djKianoosh @HMcFabulous

**Comment by yellowzapp** [comment]
merging all of the header issues into one ticket. 

https://github.com/US-CBP/cbp-theme/issues/238
