### ISSUE TITLE
.content class uses flex for no apparent reason

### ISSUE THREAD

**Issue by jscharett** [US-CBP/cbp-theme#242]
Looking at the markup/css, the .content class which is used for rendering the main content and sidebar, has styling for display flex and flex-direction row, but it doesn't appear to be necessary.  The sidebar uses fixed positioning and the main content uses side-bar-offset which sets the margin and calculates the width.  Seems like the flex styles are not really needed.

**Comment by yellowzapp** [comment]
creating ticket
