### ISSUE TITLE
Make switch "sizeable"

### ISSUE THREAD

**Issue by jscharett** [US-CBP/cbp-theme#253]
It doesn't appear that you can easily adjust the height/width of a switch.  Would be nice if the width could be auto detected to allow for any length label.  As for height, bootstrap provides various "helper classes" for adjusting the size of a control.  Would be nice if the switch respected those.

**Comment by yellowzapp** [comment]
we are working on a fix for toggles to allow variable width to accommodate various types of content such as words and icons. We will however not allow variable heights on toggles. 

please be sure to check our releases page for more information.
