### ISSUE TITLE
cbp-theme .app-header position on window scroll not matching app directory's functionality

### ISSUE THREAD

**Issue by HIGGO36** [US-CBP/cbp-theme#271]
After comparing the headers for the App Directory and the CBP Theme, noticed the <div class="app-header"> within the CBP Theme does not dynamically add or remove .top on window scroll events that are greater than the height of the universal header.

Here is a visual of the current CBP Theme app header after scrolling past universal header:

![image](https://user-images.githubusercontent.com/24257663/55257019-0ad53500-5235-11e9-9323-95e629362e1f.png)

This is how it could look after scrolling down past universal header:

![image](https://user-images.githubusercontent.com/24257663/55257049-1fb1c880-5235-11e9-931b-fd6d30f10024.png)

**Comment by davezen1** [comment]
Fixed with #275
