### ISSUE TITLE
Issue with Scoped Search

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#30]
Issue with Scoped Search - right border missing

![screen shot 2016-09-13 at 11 42 20 am](https://cloud.githubusercontent.com/assets/1034574/18480616/4d3da81e-79a7-11e6-8f87-cd370475a49e.png)

See CBP Style Guide
https://us-cbp.github.io/cbp-style-guide/docs/patterns/search.html

**Comment by djKianoosh** [comment]
In which browser? I see that right border in Chrome on Mac.

**Comment by davezen1** [comment]
Chrome Version 53.0.2785.116 (64-bit) on Mac
Firefox 48.0.1 on Mac
Safari Version 10.0 (11602.1.50.0.10) on Mac

I will check IE laters.

**Comment by davezen1** [comment]
Removed example of scoped search in Style Guide: 

Reference: https://github.com/US-CBP/cbp-style-guide/commit/1cea2411fb033e09316105676e7e8c88bef09ae3
