### ISSUE TITLE
Sidebar filter headings and content separators

### ISSUE THREAD

**Issue by djKianoosh** [US-CBP/cbp-theme#31]
Currently the sidebar headings have a border-top to mark a separation between filter content sections. 

The border is placed at the boundary of padding-top and margin-top, which looks unbalanced at the moment.

We could control it better if we put `border-bottom` on `filter-group-content` and take out `border-top` from `filter-group-title` in `_filters.scss`.

**Comment by yellowzapp** [comment]
sidebar is being deprecated as a component in the near future to be replaced with drawer components.
