### ISSUE TITLE
508 findings on Style Guide

### ISSUE THREAD

**Issue by cmterrylynn** [US-CBP/cbp-theme#39]
The Powerpoint file attached has the 508 non-compliance issues for elements of the style guide.  Not being able to tab into the actual style guide elements prevents some of the testing from being completed.  Please advise when keyboard access from the left menu into the style guide itself is addressed, and I will complete that part of the testing.
There is still significant work to be done.
[Style Guide 508 10-03-16.pptx](https://github.com/US-CBP/cbp-theme/files/508489/Style.Guide.508.10-03-16.pptx)

**Comment by djKianoosh** [comment]
I'm wondering if it's better to make 24 separate issues rather than just one... just a thought.. @davezen1 @LaurenFormichella, thoughts?

**Comment by davezen1** [comment]
@djKianoosh @cmterrylynn I plan to take this and break it up into separate issues. Some of which go to the CBP Style Guide bucket.

**Comment by cmterrylynn** [comment]
Probably, but this was my first issue in github, so I stuck with the method I use for applications ☺

Terry Lynn (TL) Sales
Section 508 and UI Tester
DHS/CBP/OIT/CSPD
571-468-5271 Desk
703-945-2777 B’Berry

**Comment by davezen1** [comment]
Closing this ticket, @cmterrylynn , per our meeting I created issues in the cbp-theme and cbp-style-guide to cover the items.
