### ISSUE TITLE
Theme timeline components

### ISSUE THREAD

**Issue by d-amit** [US-CBP/cbp-theme#40]
Per discussion with @LaurenFormichella and @HMcFabulous, timeline needs to a little polished to be more inline with the look and feel of the overall theme. Some ideas we are still discussing include...
- Making dots dark gray outlined circles with icons that can display a subtle color when hovered over. Current implementation child items within the timeline are too loud and is competing with the parent items.  
- Remove button/label style on header text - style similar to headers (clean and simple)
- Create CSS/JS to expand/collapse children of a parent

Further discussion is needed!

@HMcFabulous - Final approval on look and feel should come from you.  

<img width="1070" alt="screen shot 2016-10-06 at 5 56 52 pm" src="https://cloud.githubusercontent.com/assets/14062379/19172524/47716924-8bf0-11e6-8455-c6fde6cf246c.png">

**Comment by d-amit** [comment]
Maybe more like this what github does...

<img width="573" alt="screen shot 2016-10-06 at 6 18 16 pm" src="https://cloud.githubusercontent.com/assets/14062379/19172719/4df3401e-8bf1-11e6-94d9-037ccc847543.png">

**Comment by davezen1** [comment]
@d-amit @djKianoosh anyone working on this currently or can we table this until later?

**Comment by mkayan** [comment]
Duplicate Issue.
