### ISSUE TITLE
Pagination: Input Field Not Clear

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#47]
The blanks where the user can input the page they want to jump to needs mark up.  Label for and ID to tell them what the expected input would be.

![image](https://cloud.githubusercontent.com/assets/1034574/19334987/e753b24e-90cd-11e6-8cca-886845f6f789.png)

**Comment by yellowzapp** [comment]
ticket created.

**Comment by davezen1** [comment]
Fixed and we are moving away from this pagination component
