### ISSUE TITLE
Fix Bug within cpb-theme.js File

### ISSUE THREAD

**Issue by bkahl** [US-CBP/cbp-theme#59]
Can you guys fix the cbp-theme.js file within https://github.com/US-CBP/cbp-theme/blob/master/app/kitchensink/dist/cbp-theme.js.  I noticed that the file includes the webpack wrapper.  That's only good if the user is using node and webpack to run the cbp theme.  This won't work if the user is just downloading that file independently and trying to using it within an index.html file.  It should be able to be used either way.

**Comment by davezen1** [comment]
@bkahl is this for a static website?

**Comment by davezen1** [comment]
@bkahl did you get the issue solved. We have examples on of how to use the theme with other types of builds. Let us know if you are still stuck.

**Comment by bkahl** [comment]
I figure a work around but think you should still update this file in github for users not using webpack, otherwise, they'll have the same issues because your Readme instructions aren't very intuitive.

**Comment by davezen1** [comment]
@bkahl  Closing this issue out. We have made the README better (feel free to comment on another issue). We are now on release 1.0.0.  The build uses webpack but is UMD (Universal Module Definition) compatible.
