### ISSUE TITLE
input-group-btn is off vertically in Firefox

### ISSUE THREAD

**Issue by djKianoosh** [US-CBP/cbp-theme#6]
In Firefox 49.0a2 (2016-07-01), I see the `.input-group-btn` is off vertically from the `mdl-textfield` before it: 

![image](https://cloud.githubusercontent.com/assets/222783/16670147/dcdabae6-4466-11e6-8c57-d5462d8c354f.png)

It looks ok in IE 11 and Chrome Canary (54.0.2787.0)

**Comment by d-amit** [comment]
<img width="394" alt="screen shot 2016-07-08 at 7 29 14 pm" src="https://cloud.githubusercontent.com/assets/14062379/16704203/75531422-4542-11e6-81fc-e69250d213fe.png">
<img width="666" alt="screen shot 2016-07-08 at 7 29 49 pm" src="https://cloud.githubusercontent.com/assets/14062379/16704204/755aca32-4542-11e6-99cc-2c55169fd708.png">
