### ISSUE TITLE
Accessibility for Radio Buttons, Checkboxes, Toggle Switch

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#68]
For each of the categories in this section, focus appears to land on the active element, but there is no visual indication of focus. Let users know what section they are on by visually highlighting.

The checkboxes have an indicator but we should verify with our a11y expert. Radio buttons give no visual indication when tabbing thru, same for toggle switches.

**Comment by mkayan** [comment]
This issue is an open issue in MDL - https://github.com/google/material-design-lite/issues/5105
