### ISSUE TITLE
Input Field Underline and Select Underline Inconsistent 

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#82]
As a user, I would like consistency between regular input text fields and select fields so the same level of importance is conveyed.

Currently, select elements seem to get a light grey underline and text boxes seem to get a black underline

**Comment by dave-r** [comment]
I just noticed that it's not only the underline.  The label is also darker, at least when using a floating label.  At a glance it looks like the Select is #555 but the text box is #222
