### ISSUE TITLE
.loading style interferes with Selectize's loading class

### ISSUE THREAD

**Issue by millerbennett** [US-CBP/cbp-theme#86]
Issue:
When Selectize is performing a remote query to load its options it adds the `loading `class to its container and that causes the styles located in `cbp-theme/app/styles/custom/scss/_load-spinners.scss` to be picked up and applied to it.

Suggested resolution:
Change `loading` to `loading-indicator` or something appropriate.

**Comment by davezen1** [comment]
@millerbennett did you want to submit a pull request with a suggested fix?
