### ISSUE TITLE
Sidebar Issues with IE

### ISSUE THREAD

**Issue by r1teshkumar** [US-CBP/cbp-theme#89]
![image](https://user-images.githubusercontent.com/22313231/27441604-12510f7a-573c-11e7-96e9-7cbd25b73947.png)

**Comment by r1teshkumar** [comment]
This fix seems to address the issue

![image](https://user-images.githubusercontent.com/22313231/28430706-7af1f6b0-6d4f-11e7-87fd-a58f368fa7b8.png)

**Comment by mkayan** [comment]
Updated with last release of theme.
