### ISSUE TITLE
Labels for Select components do not disappear when active

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-theme#94]
- For selectize and select2 when input is in field the placeholder does not disappear
<img width="470" alt="screen shot 2017-07-06 at 11 17 55 am" src="https://user-images.githubusercontent.com/1034574/27918395-db1b3f1a-623c-11e7-82c7-27d7f07963cb.png">
<img width="439" alt="screen shot 2017-07-06 at 11 17 36 am" src="https://user-images.githubusercontent.com/1034574/27918396-db2308a8-623c-11e7-8a98-23f17287e380.png">

**Comment by mkayan** [comment]
Currently the is-dirty class is added/removed based on the number of "option:selected"; but when a backspace/delete is hit on the last "option:selected", it is no longer an "option" just text. 

May be if we add/remove is-dirty class based on the character length, this issue will be fixed.

**Comment by dave-r** [comment]
I was able to resolve this issue in our app by moving the the theme js script tag to the bottom of the page.  

With the script loaded near the top, the init function (below) ran before the markup was loaded, so `$('.select2-field')`  matched no elements.  So the `change` event handler that set the `is-dirty` class was never attached to the `select` elements.

		var getDirty = function getDirty(idx, el) {
			if (el !== undefined && $(el).children('select').length > 0) {
				$($(el).children('select').get(0)).change(function (ev) {
					var option = $(ev.currentTarget).find('option:selected').val();
					var action = option && option.length > 0 ? 'addClass' : 'removeClass';
					$(el)[action]('is-dirty');
				});
			}
		};
		$('.selectize-field').each(getDirty);
		$('.select2-field').each(getDirty);


Moving the script loading to the bottom allowed the markup to load before the script and the select2 floating labels started working.

**Comment by dave-r** [comment]
Sorry, closed by mistake.
