### ISSUE TITLE
SCSS dependencies are not listed in package.json

### ISSUE THREAD

**Issue by djKianoosh** [US-CBP/cbp-theme#95]
When importing the scss directly:
```scss
//test.scss
@import "cbp-theme/dist/scss/custom/scss/main";
```
We see the following error: 
```
$ node-sass --include-path=node_modules test.scss
{
  "status": 1,
  "file": "node_modules/cbp-theme/dist/scss/custom/scss/main.scss",
  "line": 3,
  "column": 1,
  "message": "File to import not found or unreadable: ~material-design-lite/src/resets/_resets.\nParent style sheet: node_modules/cbp-theme/dist/scss/custom/scss/main.scss",
  "formatted": "Error: File to import not found or unreadable: ~material-design-lite/src/resets/_resets.\n       Parent style sheet: node_modules/cbp-theme/dist/scss/custom/scss/main.scss\n        on line 3 of node_modules/cbp-theme/dist/scss/custom/scss/main.scss\n>> @import \"~material-design-lite/src/resets/_resets\";\n   ^\n"
}
```

This is because all the dependencies used in the theme's SCSS files are not listed as dependencies in `package.json`. For example, `material-design-lite` is listed under `devDependencies`.

**Comment by djKianoosh** [comment]
Also while we're at it, the `dist` directory structure is a bit unwieldy with the `scss/custom/scss` portion especially clumsy. Open to suggestions on making that better.

**Comment by davezen1** [comment]
@yogeshgadge this could change the structure of the dist directory, just a heads up.

**Comment by djKianoosh** [comment]
aha, `~` is a webpack only thing, which I am loathe to propagate... going to investigate a bit more... hang tight

**Comment by djKianoosh** [comment]
I think the best non-forcing-webpack-on-everybody solution is to say that, if you want to include scss files directly, use the node-sass cli option: `--include-path=node_modules`.  And make sure all our scss files don't use `~`, which is a webpack special symbol.

**Comment by yogeshgadge** [comment]
@djKianoosh @davezen1  I tried the equivalent of `--include-path=node_modules` you suggested and further tweaking `styles/vendor/_fontswesome.scss` in my local - works fine (this is with angular-cli which uses webpack).

I am ready to PR removing the ~. Is there anything you like to change in the directory structure ? Or you want to handle that separately ?

e.g. change in file `styles/vendor/_fontswesome.scss` (also notice `!default`) that I tried

`
@import "font-awesome/scss/variables";

// custom overrides!
$fa-font-path: "font-awesome/fonts" !default;
//
@import "font-awesome/scss/mixins";
@import "font-awesome/scss/path";
@import "font-awesome/scss/core";
@import "font-awesome/scss/larger";
@import "font-awesome/scss/fixed-width";
@import "font-awesome/scss/list";
@import "font-awesome/scss/bordered-pulled";
@import "font-awesome/scss/animated";
@import "font-awesome/scss/rotated-flipped";
@import "font-awesome/scss/stacked";
@import "font-awesome/scss/icons";

// last updated 03.15.2015
`

**Comment by djKianoosh** [comment]
@yogeshgadge do you have this in a branch? I'd like to test it out as well.

**Comment by yogeshgadge** [comment]
@djKianoosh Yes I have created a PR  https://github.com/US-CBP/cbp-theme/pull/97 Please let me know any issues. readme is updated with how to import scss.

**Comment by djKianoosh** [comment]
I might tweak the readme a little... Also `autoprefixer` is required according to the Bootstrap docs, so we probably should mention it in our own readme.  

Another thing is the readme is getting quite big, we may want to move some of these things into a wiki page.

**Comment by yogeshgadge** [comment]
Wiki page changes are here https://github.com/yogeshgadge/cbp-theme.wiki.git

**Comment by djKianoosh** [comment]
This is still an issue in 1.3.

`font-awesome` needs to be listed as a regular dependency for the sass imports to work:

```
$ node-sass --include-path=node_modules test.scss
{
  "status": 1,
  "file": "C:/Users/username/work/support/test/node_modules/cbp-theme/dist/scss/vendor/_fontawesome.scss",
  "line": 5,
  "column": 1,
  "message": "File to import not found or unreadable: font-awesome/scss/variables.\nParent style sheet: C:/Users/username/work/support/test/node_modules/cbp-theme/dist/scss/vendor/_fontawesome.scss",
  "formatted": "Error: File to import not found or unreadable: font-awesome/scss/variables.\n       Parent style sheet: C:/Users/username/work/support/test/node_modules/cbp-theme/dist/scss/vendor/_fontawesome.scss\n        on line 5 of node_modules/cbp-theme/dist/scss/vendor/_fontawesome.scss\n>> @import \"font-awesome/scss/variables\";\n   ^\n"
}
```

**Comment by djKianoosh** [comment]
Going to submit a pr soon to simply add font-awesome to dependencies instead of devDependencies...
