### ISSUE TITLE
Scrolling event handler on cbp-header role=navigation causes infinite loop in chrome

### ISSUE THREAD

**Issue by r1teshkumar** [US-CBP/cbp-theme#99]
The following event handler is causing some issues in Chrome which results in a flickering effect.

![image](https://user-images.githubusercontent.com/22313231/28339182-3c8c7c46-6bd9-11e7-8df1-80b118975e3b.png)

![image](https://user-images.githubusercontent.com/22313231/28339195-47f1d2b6-6bd9-11e7-962c-cf2ed2f0108a.png)

**Comment by d-amit** [comment]
I've seen this behavior as well and it seem to only occur for me when I click on the 'Go to Top' link within the kitchensink.
